// Generated by CoffeeScript 1.10.0
(function() {
  var esc, queries;

  queries = require('./queries');

  esc = function(esClient, indexName) {
    var _addOrUpdate, _remove, addOrUpdate, remove, removeAllSlidesForLesson, search;
    removeAllSlidesForLesson = function(lessonId, done) {
      return done();
    };
    _remove = function(arg) {
      var id, type;
      type = arg.type, id = arg.id;
      return {
        index: indexName,
        type: type,
        id: id
      };
    };
    _addOrUpdate = function(arg) {
      var doc, id, type;
      type = arg.type, id = arg.id, doc = arg.doc;
      return {
        index: indexName,
        type: type,
        id: id,
        body: {
          doc: doc,
          upsert: doc
        }
      };
    };
    remove = function(arg, done) {
      var id, type;
      type = arg.type, id = arg.id;
      return esClient["delete"](_remove({
        type: type,
        id: id
      }), function(err, resp) {
        return done(err, {});
      });
    };
    addOrUpdate = function(arg, done) {
      var doc, id, type;
      type = arg.type, id = arg.id, doc = arg.doc;
      return esClient.update(_addOrUpdate({
        type: type,
        id: id,
        doc: doc
      }), function(err, resp) {
        return done(err, {});
      });
    };
    search = function(arg, done) {
      var dict, query, type;
      type = arg.type, query = arg.query;
      dict = {
        "courseOrLesson": "course,lesson",
        "slide": "slide"
      };
      return esClient.search({
        index: indexName,
        type: dict[type],
        body: {
          query: queries[type](query)
        }
      }, function(err, res) {
        var results;
        if (err != null) {
          return done(err);
        }
        results = res.hits.hits || [];
        return done(null, results);
      });
    };
    return {
      removeAllSlidesForLesson: removeAllSlidesForLesson,
      _remove: _remove,
      _addOrUpdate: _addOrUpdate,
      remove: remove,
      addOrUpdate: addOrUpdate,
      search: search
    };
  };

  module.exports = esc;

}).call(this);
