// Generated by CoffeeScript 1.10.0
(function() {
  var _, course, lesson, slide, slideText;

  _ = require('underscore');

  course = function(course) {
    var ref;
    return {
      title: course.title,
      description: course.description,
      app: (ref = course.audience) != null ? ref.application : void 0
    };
  };

  lesson = function(lesson) {
    var ref;
    return {
      title: lesson.title,
      description: lesson.description,
      app: (ref = lesson.audience) != null ? ref.application : void 0
    };
  };

  slideText = function(slide) {
    var mediaRegex, separator;
    separator = "\n";
    mediaRegex = /\.(png|jpg|jpgeg|avi|mp3|mp4)$/i;
    if (_.isArray(slide)) {
      return slide.map(slideText).join(separator);
    } else if (_.isObject(slide)) {
      return _.values(slide).map(slideText).join(separator);
    } else if (_.isString(slide) && !(slide.match(mediaRegex))) {
      return slide;
    } else {
      return "";
    }
  };

  slide = function(slide) {
    var ref;
    return {
      name: slide.name,
      data: slide.data,
      app: (ref = slide.lesson.audience) != null ? ref.application : void 0,
      lesson: slide.lesson._id.toString(),
      text: slideText(slide.data)
    };
  };

  module.exports = {
    course: course,
    lesson: lesson,
    slide: slide
  };

}).call(this);
