// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    courseOrLesson: function(userInput) {
      var q;
      q = userInput;
      return {
        bool: {
          should: [
            {
              match: {
                title: q
              }
            }, {
              match: {
                description: q
              }
            }
          ]
        }
      };
    },
    slide: function(userInput) {
      var q;
      q = userInput;
      return {
        bool: {
          should: [
            {
              match: {
                text: q
              }
            }
          ]
        }
      };
    }
  };

}).call(this);
