// Generated by CoffeeScript 1.10.0
(function() {
  var plugin, seneca;

  seneca = require('seneca')();

  plugin = require('./index');

  seneca.use(plugin);

  seneca.ready(function(err) {
    var data;
    if (err != null) {
      console.error(err);
      return process.exit();
    } else {
      data = {
        title: "test course"
      };
      return seneca.act({
        cmd: 'update',
        type: 'course',
        id: "kjfldksjfldskj",
        doc: data
      }, function(err, res) {
        console.error(err, res);
        return seneca.act({
          cmd: 'delete',
          type: 'course',
          id: "kjfldksjfldskj"
        }, function(err, res) {
          return console.error(err, res);
        });
      });
    }
  });

}).call(this);
